name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-ec2-todo-app-auto-deploy .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/docker-ec2-todo-app-auto-deploy

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/docker-ec2-todo-app-auto-deploy
            docker rm -f todo-app || true
            docker run -d -p 4000:4000 --name todo-app ${{ secrets.DOCKER_USERNAME }}/docker-ec2-todo-app-auto-deploy
